version: "3.8"

services:

    grafana:
        image: "grafana/grafana:latest"
        ports: 
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=password
        depends_on:
            - prometheus
        networks:
            - monitoring_default    
        
    prometheus:
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - monitoring_default
   
    zipkin: 
        image: openzipkin/zipkin
        mem_limit: 700m
        ports:
        - "9411:9411"
        networks:
            - monitoring_default
     
    configserver:
        image: vishnub5329/configserver:latest
        mem_limit: 700m
        ports:
            - "8071:8071"
        depends_on: 
          - zipkin 
          
        environment:
          SPRING_PROFILES_ACTIVE: default
          SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
        networks:
            - monitoring_default
            
    eurekaserver:
        image: vishnub5329/eurekaserver:latest
        mem_limit: 700m
        ports:
            - "8070:8070"
        depends_on: 
                - configserver
        deploy: 
            restart_policy:
                condition: on-failure
                delay: 15s
                max_attempts: 3
                window: 120s
        environment:
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
            SPRING_PROFILES_ACTIVE: default
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
            SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
        networks:
            - monitoring_default       
    
    accounts:
        image: vishnub5329/accounts:latest
        mem_limit: 700m
        ports:
            - "8082:8082"
        depends_on: 
            - configserver
            - eurekaserver
        deploy:
            restart_policy:
                condition: on-failure
                delay: 30s
                max_attempts: 3
                window: 120s
        environment:
            SPRING_PROFILES_ACTIVE: default
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
            SPRING_ZIPKIN_BASEURL: http://zipkin:9411/       
        networks:
            - monitoring_default
        
    accounts1:
        image: vishnub5329/accounts:latest
        mem_limit: 700m
        ports:
            - "8083:8082"
        depends_on: 
            - configserver
            - eurekaserver
        deploy:
            restart_policy:
                condition: on-failure
                delay: 30s
                max_attempts: 3
                window: 120s
        environment:
            SPRING_PROFILES_ACTIVE: default
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka        
            SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
        networks:
            - monitoring_default
            
    loans:
        image: vishnub5329/loans:latest
        mem_limit: 700m
        ports:
            - "8091:8091"
        depends_on: 
            - configserver
            - eurekaserver
        deploy:
            restart_policy:
                condition: on-failure
                delay: 30s
                max_attempts: 3
                window: 120s
        environment:
            SPRING_PROFILES_ACTIVE: default
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
            SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
        networks:
            - monitoring_default
        
    cards:
        image: vishnub5329/cards
        mem_limit: 700m
        ports:
            - "9002:9002"
        depends_on:
            - configserver
            - eurekaserver
        deploy:
            restart_policy:
                condition: on-failure
                delay: 30s
                max_attempts: 3
                window: 120s
        environment:
            SPRING_PROFILES_ACTIVE: default
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
            SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
        networks:
            - monitoring_default
            
    gatewayserver:
        image: vishnub5329/gatewayserver
        mem_limit: 700m
        ports:
            - "8060:8060"
        depends_on: 
            - configserver
            - eurekaserver
            - accounts
            - cards
            - loans
        deploy:
            restart_policy:
              condition: on-failure
              delay: 30s
              max_attempts: 3
              window: 120s
        environment:
           SPRING_PROFILES_ACTIVE: default
           SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
           EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka            
           SPRING_ZIPKIN_BASEURL: http://zipkin:9411/ 
        networks:
            - monitoring_default    
                        
networks:
        monitoring_default: