version: "3.8"

services:

    configserver:
        image: vishnub5329/configserver:latest
        mem_limit: 700m
        ports:
            - "8071:8071"
    
    accounts:
        image: vishnub5329/accounts:latest
        mem_limit: 700m
        ports:
            - "8082:8082"
        depends_on: 
            - configserver    
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        environment:
            SPRING_PROFILES_ACTIVE: default
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
            
    loans:
        image: vishnub5329/loans:latest
        mem_limit: 700m
        ports:
            - "8091:8091"
        depends_on: 
            - configserver
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        environment:
            SPRING_PROFILES_ACTIVE: default
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
            
    cards:
        image: vishnub5329/cards
        mem_limit: 700m
        ports:
            - "9002:9002"
        depends_on:
            - configserver
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        environment:
            SPRING_PROFILES_ACTIVE: default
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
            
            