{{- define "common.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.deploymentLabel }}
data:
    SPRING_ZIPKIN_BASEURL: {{ .Values.global.zipkinBaseURL }}
    SPRING_PROFILES_ACTIVE: {{ .Values.global.activeProfile }}
    SPRING_CONFIG_IMPORT: {{ .Values.global.configServerURL }}
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .Values.global.eurekaServerURL }}
{{- end -}}    